// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1
TEST_CASE("Ex1", "[example]")
{
	const int N = 10;
	Students s[N];

	makeStudents(s, N);
	cout << "Initial Student's Struct Array \n";
	printStudents(s, N);
	bubbleSort(s, N);
	cout << "After Sorting \n";
	printStudents(s, N);

	REQUIRE(s[0].sid == 10001111);
	REQUIRE(s[1].sid == 10005566);
	REQUIRE(s[2].sid == 10006677);
	REQUIRE(s[3].sid == 10007766);
	REQUIRE(s[4].sid == 10007777);
	REQUIRE(s[5].sid == 10007777);
	REQUIRE(s[6].sid == 10007777);
	REQUIRE(s[7].sid == 10008888);
	REQUIRE(s[8].sid == 10009900);
	REQUIRE(s[9].sid == 10009999);
}
